GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ HTTP/1.1
content-type: application/json

{
    "content": "REST Client FTW!",
    "important": true
}

###
DELETE http://localhost:3001/api/notes/63c6a277212a27318d0d5c9d